# Generated by Django 4.2.2 on 2026-02-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="company",),
    ]
