# Generated by Django 4.2.2 on 2026-02-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_company_admin',
            field=models.BooleanField(default=False),
        ),
    ]
