# Generated by Django 4.2.2 on 2026-04-18 09:21

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_company_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Kada buvo užfiksuotas šis skaičius')),
                ('active_count', models.PositiveIntegerField(help_text='Aktyvių darbuotojų skaičius tuo metu')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_count_logs', to='users.company')),
            ],
            options={
                'verbose_name': 'Darbuotojų skaičiaus įrašas',
                'verbose_name_plural': 'Darbuotojų skaičiaus įrašai',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_employee', models.DecimalField(decimal_places=2, help_text='Kaina už vieną aktyvų darbuotoją per mėnesį (EUR)', max_digits=8)),
                ('minimum_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimalus mėnesinis mokestis (EUR)', max_digits=8)),
                ('contract_start', models.DateField(help_text='Sutarties pradžios data')),
                ('contract_end', models.DateField(blank=True, help_text='Sutarties pabaigos data (palikite tuščią jei neterminuota)', null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_settings', to='users.company')),
            ],
            options={
                'verbose_name': 'Sutarties nustatymai',
                'verbose_name_plural': 'Sutarčių nustatymai',
            },
        ),
    ]
