# Generated by Django 4.2.2 on 2026-04-18 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_employeecountlog_contractsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsettings',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='users.company'),
        ),
    ]
