# Generated by Django 4.2.2 on 2026-05-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_contractsettings_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email_domain',
            field=models.CharField(blank=True, default='', help_text='El. pašto domenas (pvz. orbigrow.lt). Vartotojai su šiuo domenu bus automatiškai priskirti šiai įmonei.', max_length=255),
        ),
    ]
