services:
  db:
    image: postgres:13
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build: .
    command: sh -c "npm install && npm run build && python manage.py collectstatic --noinput && python manage.py migrate && gunicorn feedbackas.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/app
    # Port mapping added for local access
    ports:
      - "8000:8000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.kudosly.rule=Host(`kudosly.lt`) || Host(`www.kudosly.lt`)
      - traefik.http.routers.kudosly.entrypoints=websecure
      - traefik.http.routers.kudosly.tls.certresolver=letsencrypt
      - traefik.http.services.kudosly.loadbalancer.server.port=8000
      - traefik.docker.network=traefik-proxy
    networks:
      - traefik-proxy
      - default
    depends_on:
      - db
      - redis
    restart: unless-stopped
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    env_file:
      - .env
    # Do not publish Redis publicly

  worker:
    build: .
    command: sh -c "python manage.py qcluster"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    restart: unless-stopped
    env_file:
      - .env

volumes:
  postgres_data:

networks:
  traefik-proxy:
    external: true
