# Generated by Django 4.2.2 on 2026-02-17 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("comment", models.TextField(blank=True, null=True)),
                ("due_date", models.DateField()),
                ("status", models.CharField(default="pending", max_length=20)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "requested_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="made_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField(help_text="Bendras įvertinimas")),
                ("teamwork_rating", models.IntegerField(default=5)),
                ("communication_rating", models.IntegerField(default=5)),
                ("initiative_rating", models.IntegerField(default=5)),
                ("technical_skills_rating", models.IntegerField(default=5)),
                ("problem_solving_rating", models.IntegerField(default=5)),
                ("keywords", models.CharField(max_length=255)),
                ("comments", models.TextField(blank=True)),
                ("feedback", models.TextField()),
                (
                    "feedback_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="feedbackas.feedbackrequest",
                    ),
                ),
            ],
        ),
    ]
