# Generated by Django 4.2.26 on 2025-11-18 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('keywords', models.CharField(max_length=255)),
                ('feedback', models.TextField()),
                ('feedback_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='feedbackas.feedbackrequest')),
            ],
        ),
    ]
