# Generated by Django 4.2.2 on 2025-11-19 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='communication_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='initiative_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='problem_solving_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='teamwork_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='feedback',
            name='technical_skills_rating',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='rating',
            field=models.IntegerField(help_text='Bendras įvertinimas'),
        ),
    ]
