# Generated by Django 4.2.2 on 2026-02-20 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0002_trait_questionnaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='questionnaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_requests', to='feedbackas.questionnaire'),
        ),
    ]
