# Generated by Django 4.2.2 on 2025-11-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0003_feedback_communication_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
