# Generated by Django 4.2.2 on 2026-02-20 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0003_feedbackrequest_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraitRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trait_ratings', to='feedbackas.feedback')),
                ('trait', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feedbackas.trait')),
            ],
            options={
                'unique_together': {('feedback', 'trait')},
            },
        ),
    ]
