# Generated by Django 4.2.2 on 2026-02-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedbackas", "0004_traitrating"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="extracted_improvements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="feedback",
            name="extracted_strengths",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
