# Generated by Django 4.2.2 on 2025-11-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0004_add_comments_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
