# Generated by Django 4.2.2 on 2025-11-27 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0005_feedbackrequest_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackrequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
