# Generated by Django 4.2.2 on 2026-03-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0005_feedback_extracted_improvements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='is_team',
            field=models.BooleanField(default=False),
        ),
    ]
