# Generated by Django 4.2.2 on 2026-03-28 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_company_is_active'),
        ('feedbackas', '0006_questionnaire_is_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='target_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_questionnaires', to='users.department'),
        ),
    ]
