# Generated by Django 4.2.2 on 2026-04-19 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_contractsettings_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedbackas', '0007_questionnaire_target_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(help_text="Pvž., 'feedback_generation', 'feedback_analysis'", max_length=100)),
                ('model_name', models.CharField(max_length=100)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to='users.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
