# Generated by Django 4.2.2 on 2026-04-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0009_feedback_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='total_cost',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=15),
        ),
    ]
