# Generated by Django 4.2.2 on 2026-04-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0011_feedbackrequest_is_self_initiated'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personal_form_enabled', models.BooleanField(default=True, help_text="Įjungti 'Individuali forma' funkcionalumą visai platformai.")),
                ('team_form_enabled', models.BooleanField(default=True, help_text="Įjungti 'Komandinė forma' funkcionalumą visai platformai.")),
            ],
            options={
                'verbose_name_plural': 'Global Settings',
            },
        ),
    ]
