# Generated by Django 4.2.2 on 2026-05-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0012_globalsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_hero_title', models.CharField(default='Skatinkite atvirą komandos kultūrą', max_length=255)),
                ('index_hero_desc', models.TextField(default='Mūsų platforma padeda lengvai rinkti ir analizuoti atsiliepimus. Išryškinkite stiprybes ir padėkite savo darbuotojams augti kartu.')),
                ('index_features_title', models.CharField(default='Kodėl verta rinktis mus?', max_length=255)),
                ('index_feature1_title', models.CharField(default='Atviras Grįžtamasis Ryšys', max_length=255)),
                ('index_feature1_desc', models.TextField(default='Skatinkite skaidrumą ir asmeninį augimą su atvirais, vardiniais kolegų atsiliepimais bei vertinimais.')),
                ('index_feature2_title', models.CharField(default='Dirbtinio Intelekto Įžvalgos', max_length=255)),
                ('index_feature2_desc', models.TextField(default='AI algoritmai sistemina gautus atsiliepimus, išryškindami asmenines stiprybes ir aiškias sritis, kuriose vertėtų tobulėti.')),
                ('index_feature3_title', models.CharField(default='Paprasta Naudoti', max_length=255)),
                ('index_feature3_desc', models.TextField(default='Intuityvi sąsaja tiek administratoriams, tiek darbuotojams. Pradėkite per kelias minutes.')),
                ('index_howitworks_title', models.CharField(default='Kaip tai veikia?', max_length=255)),
                ('index_step1_title', models.CharField(default='Paprašykite Atsiliepimo', max_length=255)),
                ('index_step1_desc', models.TextField(default='Pasirinkite kolegą ir išsiųskite prašymą įvertinti jūsų darbą keliais paspaudimais.')),
                ('index_step2_title', models.CharField(default='Gaukite Įvertinimą', max_length=255)),
                ('index_step2_desc', models.TextField(default='Kolegos atvirai atsako į išsamius kompetencijų ir asmeninių savybių klausimus.')),
                ('index_step3_title', models.CharField(default='Analizuokite su AI', max_length=255)),
                ('index_step3_desc', models.TextField(default='Dirbtinis intelektas praskenuoja komentarus ir pateikia aiškias stiprybes bei tobulėjimo sritis.')),
                ('index_cta_title', models.CharField(default='Pasiruošę pagerinti komandos ryšį?', max_length=255)),
                ('index_cta_desc', models.TextField(default='Prisijunkite prie įmonių, kurios naudoja atsiliepimus savo augimui skatinti. Pradėkite nemokamą bandomąjį laikotarpį šiandien.')),
                ('about_hero_title', models.CharField(default='Apie Mūsų Komandą', max_length=255)),
                ('about_hero_desc', models.TextField(default='Orbigrow.lt tikslas – padėti organizacijoms sukurti atvirą grįžtamojo ryšio kultūrą ir paskatinti kiekvieno darbuotojo augimą.')),
                ('about_mission_title', models.CharField(default='Mūsų Misija', max_length=255)),
                ('about_mission_desc1', models.TextField(default='Tikime, kad nuolatinis ir atviras kolegų vertinimas yra pagrindinis komandos tobulėjimo variklis. Dažnai grįžtamasis ryšys įmonėse būna pamirštamas, paliekamas tik metiniams pokalbiams arba anoniminis, kas trukdo konstruktyviam dialogui.')),
                ('about_mission_desc2', models.TextField(default='Mūsų platforma sprendžia šią problemą siūlydama patogų, vardinį ir struktūrizuotą atsiliepimų rinkimo procesą, kurį papildo modernus dirbtinis intelektas (AI), išryškinantis esmines stiprybes bei pastangas.')),
                ('about_values_title', models.CharField(default='Mūsų Vertybės', max_length=255)),
                ('about_values_subtitle', models.CharField(default='Principai, kuriais vadovaujamės kurdami platformą', max_length=255)),
                ('about_value1_title', models.CharField(default='Skaidrumas', max_length=255)),
                ('about_value1_desc', models.TextField(default='Mes nesislepiame už anonimiškumo. Tikime, kad tikras tobulėjimas prasideda nuo atviro ir nuoširdaus grįžtamojo ryšio.')),
                ('about_value2_title', models.CharField(default='Inovacijos', max_length=255)),
                ('about_value2_desc', models.TextField(default='AI integracija leidžia sutaupyti valandas laiko analizuojant dešimtis komentarų, paverčiant juos aiškiomis įžvalgomis.')),
                ('about_value3_title', models.CharField(default='Paprastumas', max_length=255)),
                ('about_value3_desc', models.TextField(default='Platforma sukurta taip, kad prašyti ir suteikti grįžtamąjį ryšį užtruktų vos kelis paspaudimus.')),
                ('about_value4_title', models.CharField(default='Palaikymas', max_length=255)),
                ('about_value4_desc', models.TextField(default='Mūsų tikslas ne kritikuoti, o auginti. Viskas orientuota į komandos nario stiprybių ugdymą.')),
            ],
            options={
                'verbose_name_plural': 'Page Descriptions',
            },
        ),
    ]
