# Generated by Django 4.2.2 on 2026-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0013_pagedescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedescription',
            name='security_content',
            field=models.TextField(default='<h2>Mūsų saugumo praktikos</h2><p>Čia pateikiama informacija apie tai, kaip saugome jūsų duomenis.</p>'),
        ),
    ]
