# Generated by Django 4.2.2 on 2026-05-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0014_pagedescription_security_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedescription',
            name='maintenance_desc',
            field=models.TextField(default='Šiuo metu atnaujiname sistemą. Užsukite netrukus!'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='maintenance_mode',
            field=models.BooleanField(default=False, help_text="Įjungus šį režimą, pradiniame puslapyje bus rodomas 'Greitai pradėsime' pranešimas."),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='maintenance_title',
            field=models.CharField(default='Greitai pradėsime', max_length=255),
        ),
    ]
