# Generated by Django 4.2.2 on 2026-05-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0015_pagedescription_maintenance_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagedescription',
            name='about_hero_desc_en',
            field=models.TextField(blank=True, default="Orbigrow.lt's goal is to help organizations create an open feedback culture and foster the growth of every employee."),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='about_hero_title_en',
            field=models.CharField(blank=True, default='About Our Team', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='about_mission_desc1_en',
            field=models.TextField(blank=True, default='We believe that continuous and open peer evaluation is the main driver of team development. Often, feedback in companies is forgotten, left only for annual reviews, or kept anonymous, which hinders constructive dialogue.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='about_mission_desc2_en',
            field=models.TextField(blank=True, default='Our platform solves this problem by offering a convenient, named, and structured feedback collection process, complemented by modern artificial intelligence (AI) that highlights essential strengths and efforts.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='about_mission_title_en',
            field=models.CharField(blank=True, default='Our Mission', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='about_value1_desc_en',
            field=models.TextField(blank=True, default='We do not hide behind anonymity. We believe that real improvement starts with open and honest feedback.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='about_value1_title_en',
            field=models.CharField(blank=True, default='Transparency', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='about_value2_desc_en',
            field=models.TextField(blank=True, default='AI integration saves hours of time analyzing dozens of comments, turning them into clear insights.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='about_value2_title_en',
            field=models.CharField(blank=True, default='Innovation', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='about_value3_desc_en',
            field=models.TextField(blank=True, default='The platform is designed so that requesting and providing feedback takes just a few clicks.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='about_value3_title_en',
            field=models.CharField(blank=True, default='Simplicity', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='about_value4_desc_en',
            field=models.TextField(blank=True, default="Our goal is not to criticize, but to grow. Everything is focused on developing the team member's strengths."),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='about_value4_title_en',
            field=models.CharField(blank=True, default='Support', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='about_values_subtitle_en',
            field=models.CharField(blank=True, default='Principles that guide us in building the platform', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='about_values_title_en',
            field=models.CharField(blank=True, default='Our Values', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_cta_desc_en',
            field=models.TextField(blank=True, default='Join companies that use feedback to drive their growth. Start your free trial today.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_cta_title_en',
            field=models.CharField(blank=True, default='Ready to improve team connection?', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_feature1_desc_en',
            field=models.TextField(blank=True, default='Encourage transparency and personal growth with open, named peer reviews and ratings.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_feature1_title_en',
            field=models.CharField(blank=True, default='Open Feedback', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_feature2_desc_en',
            field=models.TextField(blank=True, default='AI algorithms systematize the received feedback, highlighting personal strengths and clear areas for improvement.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_feature2_title_en',
            field=models.CharField(blank=True, default='Artificial Intelligence Insights', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_feature3_desc_en',
            field=models.TextField(blank=True, default='Intuitive interface for both administrators and employees. Get started in minutes.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_feature3_title_en',
            field=models.CharField(blank=True, default='Easy to Use', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_features_title_en',
            field=models.CharField(blank=True, default='Why choose us?', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_hero_desc_en',
            field=models.TextField(blank=True, default='Our platform helps you easily collect and analyze feedback. Highlight strengths and help your employees grow together.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_hero_title_en',
            field=models.CharField(blank=True, default='Foster an open team culture', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_howitworks_title_en',
            field=models.CharField(blank=True, default='How it works?', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_step1_desc_en',
            field=models.TextField(blank=True, default='Select a colleague and send a request to evaluate your work in a few clicks.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_step1_title_en',
            field=models.CharField(blank=True, default='Request Feedback', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_step2_desc_en',
            field=models.TextField(blank=True, default='Colleagues openly answer detailed questions about competencies and personal traits.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_step2_title_en',
            field=models.CharField(blank=True, default='Get Evaluated', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_step3_desc_en',
            field=models.TextField(blank=True, default='Artificial intelligence scans comments and provides clear strengths and areas for improvement.'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='index_step3_title_en',
            field=models.CharField(blank=True, default='Analyze with AI', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='maintenance_desc_en',
            field=models.TextField(blank=True, default='We are currently updating our system. Please check back soon!'),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='maintenance_title_en',
            field=models.CharField(blank=True, default='Coming Soon', max_length=255),
        ),
        migrations.AddField(
            model_name='pagedescription',
            name='security_content_en',
            field=models.TextField(blank=True, default='<h2>Our Security Practices</h2><p>Here is information on how we protect your data.</p>'),
        ),
    ]
