# Generated by Django 4.2.2 on 2026-05-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackas', '0016_pagedescription_about_hero_desc_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='language_switcher_enabled',
            field=models.BooleanField(default=True, help_text='Įjungti kalbų pasirinkimą (LT/EN) visoje platformoje.'),
        ),
    ]
