import re

translations = {
    'Password': 'Password',
    'Password confirmation': 'Password confirmation',
    'Lietuvių': 'Lithuanian',
    'English': 'English',
    'Apie mus': 'About us',
    'Pradžia': 'Home',
    'Saugumas': 'Security',
    'Prietaisų skydelis': 'Dashboard',
    'Prisijungti': 'Login',
    'Jūs peržiūrite sistemą kaip': 'You are viewing the system as',
    'Grįžti į Superadmin': 'Return to Superadmin',
    'Pagrindinis': 'Home',
    'Mano Užduotys': 'My Tasks',
    'Mano Komanda': 'My Team',
    'Individuali forma': 'Personal Form',
    'Įmonės valdymas': 'Company Management',
    'Rezultatai': 'Results',
    'Komandos statistika': 'Team Statistics',
    'Įmonės': 'Companies',
    'Supervartotojai': 'Superusers',
    'Vartotojai': 'Users',
    'Aprašymai': 'Descriptions',
    'Atsijungti': 'Logout',
    'Atgal': 'Back',
    'Atsiliepimas apie': 'Feedback about',
    'Mokosi': 'Learning',
    'Daro': 'Doing',
    'Varo': 'Driving',
    'Pavyzdys': 'Example',
    'Pasirinkite vieną iš lygių aukščiau': 'Choose one of the levels above',
    'Raktiniai žodžiai': 'Keywords',
    'Įveskite žodį ir spauskite Enter arba kablelį...': 'Enter a word and press Enter or comma...',
    'Rinktis iš debesies': 'Choose from cloud',
    'Raktinių žodžių debesis': 'Keyword cloud',
    'Komentarai': 'Comments',
    'Įrašykite laisvos formos komentarus apie kolegą...': 'Enter free-form comments about the colleague...',
    'Išsamus atsiliepimas (AI)': 'Detailed feedback (AI)',
    'Pateikite išsamesnį komentarą...': 'Provide a more detailed comment...',
    'Generuoti AI juodraštį': 'Generate AI draft',
    'Pasirinkite visas savybes ir bent 3 raktinius žodžius': 'Select all traits and at least 3 keywords',
    'Patvirtinti ir siųsti': 'Confirm and send',
    'Labas,': 'Hello,',
    'Štai kas šiandien vyksta su jūsų grįžtamuoju ryšiu.': 'Here is what is happening with your feedback today.',
    'Prašyti įvertinimo': 'Request rating',
    'Siųsti įvertinimą': 'Send rating',
    'Jūs jau žinote. Mes tiesiog randame žodžius.': 'You already know. We just find the words.',
    'Pasirinkite raktinius žodžius, pridėkite komentarą — sistema per kelias sekundes pavers tai aiškiu, į augimą orientuotu grįžtamuoju ryšiu.': 'Select keywords, add a comment — the system will turn it into clear, growth-oriented feedback in seconds.',
    'Paprašykite pirmojo įvertinimo': 'Request your first rating',
    'Laukiančios apklausos': 'Pending surveys',
    'Laukiama atsakymo': 'Awaiting response',
    'Užpildytos apklausos': 'Completed surveys',
    'Iš viso surinkta atsakymų': 'Total responses collected',
    'Mano išsiųsta': 'My sent',
    'Komandos nariams išsiųstas ryšys': 'Feedback sent to team members',
    'Komandos veikla': 'Team activity',
    'Rodyti komandą': 'Show team',
    'prieš': 'ago',
    'Komandos veiklos dar nėra. Pakvieskite narius.': 'No team activity yet. Invite members.',
    'Pakviesti narius': 'Invite members',
    'Prašyti atsiliepimo': 'Request feedback',
    'Kolega': 'Colleague',
    'Projekto pavadinimas': 'Project name',
    'Pavadinimas': 'Title',
    'Komentaras': 'Comment',
    'Žinutė...': 'Message...',
    'Pateikti iki': 'Due date',
    'Atšaukti': 'Cancel',
    'Siųsti': 'Send',
    'Siųsti atsiliepimą': 'Send feedback',
    'Pasirinkti': 'Select',
    'Klaida:': 'Error:',
    'Pasirinkite kolegą!': 'Select a colleague!',
    'Mano rezultatai': 'My results',
    'Jūsų asmeninio tobulėjimo suvestinė.': 'Your personal development summary.',
    'Visi': 'All',
    'Mėnuo': 'Month',
    'Ketvirtis': 'Quarter',
    'Metai': 'Year',
    'Kompetencijų vertinimas': 'Competency assessment',
    'Kaip jus apibūdina': 'How you are described',
    'Kol kas nėra raktinių žodžių.': 'No keywords yet.',
    'Saugumo užtikrinimas': 'Security assurance',
    'Saugumo Užtikrinimas': 'Security Assurance',
    'Jūsų duomenų saugumas ir privatumas yra mūsų prioritetas.': 'Your data security and privacy is our priority.',
    'Komandos nariai': 'Team members',
    'Bendraukite ir keiskitės grįžtamuoju ryšiu su kolegomis.': 'Communicate and exchange feedback with colleagues.',
    'Skyrius nepriskirtas': 'Department not assigned',
    'Reitingas': 'Rating',
    'Laukiama': 'Pending',
    'Jau turite neužpildytą užklausą': 'You already have an unfilled request',
    'Vertinti': 'Evaluate',
    'Tuščia komanda': 'Empty team',
    'Jūsų komandoje dar nėra narių. Pakvieskite kolegas prisijungti prie platformos, kad galėtumėte keistis atsiliepimais.': 'No members in your team yet. Invite colleagues to join the platform to exchange feedback.',
    'Bendra komandos kompetencijų ir aktyvumo apžvalga': 'General overview of team competencies and activity',
    'Komandos vidurkis': 'Team average',
    'iš 4': 'out of 4',
    'Narių skaičius': 'Number of members',
    'nariai': 'members',
    'Gauta atsiliepimų': 'Feedback received',
    'iš viso': 'total',
    'Komandos Kompetencijos': 'Team Competencies',
    'Nėra pakankamai duomenų kompetencijoms rodyti.': 'Not enough data to display competencies.',
    'Narių Įvertinimai': 'Member Ratings',
    'Darbuotojas': 'Employee',
    'Atsiliepimų': 'Feedback',
    'Vidurkis': 'Average',
    'Lygis': 'Level',
    'Komandoje kol kas nėra narių su atsiliepimais.': 'No members with feedback in the team yet.'
}

with open('locale/en/LC_MESSAGES/django.po', 'r') as f:
    content = f.read()

def replacer(match):
    msgid = match.group(1)
    if msgid in translations:
        return f'msgid "{msgid}"\nmsgstr "{translations[msgid]}"'
    return match.group(0)

# Replace msgid/msgstr pairs
# Handle multi-line msgid if necessary, but here we assume simple ones first
content = re.sub(r'msgid "([^"]+)"\nmsgstr ""', replacer, content)

with open('locale/en/LC_MESSAGES/django.po', 'w') as f:
    f.write(content)

print("Translated django.po")
